### ISSUE TITLE
Reproducing the results in Table 1 on Set3c.

### ISSUE THREAD

**Issue by qiaopTDUN** [wustl-cig/DRP#1]
I tried to reproduce the results in according Table 1 on Set3c (code in both this repository and the supplementary material appended in https://openreview.net/pdf?id=x7d1qXEn1e). After preparing the virtual environment and SwinIR pretrained models, I tried the script DRP_deblur_k1.py in deblur_experments. The results were different from those reported in Table 1 on Set3c. I would like to know what adjustments are needed to reproduce the results of Table 1 on Set3c, in addition to the steps mentioned. Looking forward to your reply.

**Comment by Hu-Yuyang** [comment]
Thanks for following up our work! We now uploaded the whole virtual environment configuration to Github. Could you please retry it? Thanks!

**Comment by qiaopTDUN** [comment]
Thanks for your kindly reply. It solved all my questions. Nice job.
