### ISSUE TITLE
test on 4x sisr

### ISSUE THREAD

**Issue by ChongWang1024** [wustl-cig/DRP#2]
Hi, 
Thanks for sharing the code for this interesting work.
When I run 4x sisr (directly modifying sf=4 in _DRP_sisr_2x_k1.py_), it reports an error as below.
This error seems to be related to _imresize_ function in _util_sr.py_, could you please help me figure out it?
Many thanks in advance!
![image](https://github.com/wustl-cig/DRP/assets/95559984/5835acee-b873-47df-bbdb-da61f4ee4880)

**Comment by Hu-Yuyang** [comment]
Thank you for taking the time to read our paper! The 'imresize' function used in this file mirrors the 'imresize' function of the MATLAB version, supporting bicubic down/super-resolution. You have the flexibility to interchange the 'imresize' function with alternative bicubic resize functions available in different packages.

Moreover, if you wish to adapt this version of 'imresize' for 4x down-resolution for this setting directly, consider increasing the kernel_width parameter from 4 to 5 or beyond.

**Comment by ChongWang1024** [comment]
Got it!
Thank you so much. That completely addressed my issue.
